bExecuteScriptsOnSwitch = 0
bExecuteScriptsOnConfirm = 0
bExecuteScriptsOnExit = 1
bExitSumbenuAfterConfirm = 0
bAllowLoopingUpDown = 1
scrExecuteScriptOnStart = -1
bEnableUISounds = 1
ds_list_add(liMenuItemNames, "No Hat")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, -2)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Top Hat")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 0)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Mini Shelly")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 1)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Unicorn Horn")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 2)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Human")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 3)
ds_list_add(liMenuItemNames, "Winter")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 4)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Squid")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 5)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)
ds_list_add(liMenuItemNames, "Poop")
ds_list_add(liMenuItemInstances, -1)
ds_list_add(liMenuItemScripts, gml_Script_scr_set_default_hat)
ds_list_add(liMenuItemScriptArguments, 6)
ds_list_add(liMenuItemTooltipScript, -1)
ds_list_add(liMenuItemTooltipArgument, -1)