global.setting_squid_in_editor = false
global.setting_epilepsy_warning = true
global.setting_multiframe_loading = false
global.setting_camzoom_max = 6
global.setting_camzoom_min = 0.25
global.setting_intense_backgrounds = 1
global.setting_squid_constant_opacity = false
global.setting_skip_title_animation = false
global.setting_show_hotkeys_overlay = true
global.setting_place_multiple_players = false
global.setting_player_body = -1
global.setting_player_shell = -1
global.setting_player_outline = -1
global.setting_player_eye = -1
global.setting_player_death = -1
global.setting_player_spotlight = -1
global.setting_player_spotlight_dark = -1
global.setting_player_flare = -1
global.setting_player_trail = -1
global.setting_default_hat = -1
global.setting_squid_color = -1
global.setting_optimized_wires = false
global.setting_funny_squid = false
global.setting_blood_mode = false
global.setting_fully_reset_new_levels = false
global.setting_multiframe_loading_wires = false
global.setting_unicorn_horn_ball_override = true
global.setting_campaign_exploration_mode = false
global.setting_place_multiple_oneAtATime_objs = false
global.restart_invincible_mode = false
global.setting_global_inspector_available = false 
global.setting_save_states = false
global.setting_respawn_time = 0
global.setting_input_display = false
global.setting_legitimacy_marker = false
global.setting_noclip_indicator = false
global.setting_copy_tool_bypass = false
global.setting_noclip_indicator_color = c_red
global.setting_noclip_indicator_transparency = 0.2
global.setting_speedrun_timer_attempt = false 
global.setting_enter_value_manually = true
global.setting_speedrun_reset_button = false

global.setting_shw_theme_titleBar = make_color_rgb(0.04 * 255, 0.04 * 255, 0.04 * 255)
global.setting_shw_theme_titleBarActive = make_color_rgb(0.16 * 255, 0.29 * 255, 0.48 * 255)
global.setting_shw_theme_titleBarCollapsed = make_color_rgb(0.0 * 255, 0.0 * 255, 0.0 * 255)
global.setting_shw_theme_windowBG = make_color_rgb(0.06 * 255, 0.06 * 255, 0.06 * 255)

global.setting_show_console = true